---
- name: Converge
  hosts: all
  become: true
  gather_facts: true

  vars:
    git_username: root
    git_groupname: root
    git_repository_destination: /root
    git_repositories:
      - repo: https://github.com/buluma/ansible-role-bootstrap
        dest: bootstrap
      - repo: https://github.com/buluma/ansible-role-bootstrap
        dest: bootstrap-force
        force: true
      - repo: https://github.com/buluma/ansible-role-bootstrap
        dest: bootstrap-version
        version: "v2.0.0"

  pre_tasks:
    - name: Update apt cache.
      apt: update_cache=true cache_valid_time=600
      when: ansible_os_family == 'Debian'

  roles:
    - role: ansible-role-git
