---
- name: Prepare
  hosts: all
  gather_facts: false
  become: true
  serial: 30%

  pre_tasks:
    - name: Update apt cache.
      apt: update_cache=true cache_valid_time=600
      when: ansible_os_family == 'Debian'

  roles:
    - role: buluma.bootstrap
